POST http://localhost:3001/api/notes/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpZ2kiLCJpZCI6IjY3ZDM0MmRiZmI2MTdmY2E1ZDhhZGIyMiIsImlhdCI6MTc0MTg5OTg3OH0.Od7qfhSB7wPXR0hlNo8gnJLeFJCWjEqQXfAjnwKVewY

{
    "content": "This is a new note",
    "important": true,
    "userId": "67d342dbfb617fca5d8adb22"
}
###
GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/6794b46b1550068467534c8e